In [0]:
import numpy as np

# Матрица из нулей и единиц

In [0]:
def decorate_matrix(inputValue):
    try:
        inputValue = int(inputValue)
    except:
        return('input value should be integer')
    if inputValue <= 0:
        return('input value should be greater than 0')
    elif inputValue == 1 or inputValue == 2:
        return np.ones((inputValue,inputValue))
    else:
        ones = np.ones((inputValue,inputValue))
        zeros = np.zeros((inputValue - 2, inputValue - 2))
        ones[1:inputValue - 1, 1:inputValue - 1] =  zeros
        return ones

In [32]:
inputValue = input()
print(decorate_matrix(inputValue))

3
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


# Моделирование нескольких случайных блужданий за раз

In [0]:
def random_walks(steps):
    results = []
    for step in steps:
        results.append(np.cumsum(step))
    return results

In [0]:
different_steps = []
ways = 5000
for _ in range(ways):
    number = 1000
    draws = np.random.randint(0, 2, size = number)
    steps = np.where(draws > 0, 1, -1)
    different_steps.append(steps)

In [0]:
walks = random_walks(different_steps)

In [36]:
print('Min along all the walks = {}'.format(np.min([np.min(walk) for walk in walks])))
print('Max along all the walks = {}'.format(np.max([np.max(walk) for walk in walks])))
print('Min time of getting 30 or 30 along all the walks = {}'.format(np.min([(np.abs(walk)>30).argmax() for walk in walks \
                                                      if (True in (np.abs(walk)>30))])))

Min along all the walks = -108
Max along all the walks = 125
Min time of getting 30 or 30 along all the walks = 62
